apiVersion: v1
kind: Pod
metadata:
  name: kafka-client
  namespace: default
spec:
  containers:
  - name: kafka-client
    image: bitnami/postgresql
    command:
      - sh
      - -c
      - "exec tail -f /dev/null"
