apiVersion: v1
kind: Pod
metadata:
  name: ksql-client
  namespace: default
spec:
  containers:
  - name: ksql-client
    image: confluentinc/cp-ksql-cli
    command:
      - sh
      - -c
      - "exec tail -f /dev/null"
