apiVersion: v1
kind: Pod
metadata:
  name: ksql-datagen
  namespace: default
spec:
  containers:
  - name: ksql-datagen
    image: confluentinc/ksql-examples
    command:
      - sh
      - -c
      - "ksql-datagen quickstart=pageviews format=delimited topic=pageviews bootstrap-server=confluent-cp-kafka-headless:9092"
