apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: ksql-datagen
  namespace: default
  labels:
    app: ksql-datagen
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ksql-datagen
  template:
    metadata:
      labels:
        app: ksql-datagen
    spec:
      containers:
      - name: ksql-datagen
        image: confluentinc/ksql-examples
        command:
          - sh
          - -c
          - "ksql-datagen quickstart=pageviews format=delimited topic=pageviews bootstrap-server=confluent-cp-kafka-headless:9092"
      - name: prometheus-jmx-exporter
        image: solsson/kafka-prometheus-jmx-exporter
        command:
          - sh 
          - -c
          - "exec tail -f /dev/null"
      #  - java
      #  - -XX:+UnlockExperimentalVMOptions
      #  - -XX:+UseCGroupMemoryLimitForHeap
      #  - -XX:MaxRAMFraction=1
      #  - -XshowSettings:vm
      #  - -jar
      #  - jmx_prometheus_httpserver.jar
      #  - 5556
      #  - /etc/jmx-ksql-server/jmx-ksql-server-prometheus.yml
        ports: 
        - containerPort: 5556
