apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: ksql-datagen
  namespace: default
  labels:
    app: ksql-datagen
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ksql-datagen
  template:
    metadata:
      labels:
        app: ksql-datagen
    spec:
      containers:
      - name: ksql-datagen
        image: confluentinc/ksql-examples
        command:
          - sh
          - -c
          - "ksql-datagen quickstart=pageviews format=avro topic=pageviews schemaRegistryUrl=http://confluent-cp-schema-registry:8081 bootstrap-server=confluent-cp-kafka-headless:9092"
          #- "ksql-datagen quickstart=pageviews format=delimited topic=pageviews bootstrap-server=confluent-cp-kafka-headless:9092"
