---
apiVersion: v1
kind: PersistentVolume
metadata: 
  name: zookeeper-datalogdir-pv
  labels:
    type: local
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  hostPath:
    path: /home/ccma/data/zookeeper-datalogdir-data
  persistentVolumeReclaimPolicy: Retain
